<template>
  <Nav />
  <section class="section Admin-Section bg-white">
    <div class="container">
      <div class="row bg-gray">
        <div class="col-lg-4">
          <h2 class="title text-dark">Order sammanställning</h2>
          <div class="card">
            <div class="card-body">
              <div
                v-for="(product, i) in cart"
                :key="i"
                class="media align-items-center mb-3"
              >
                <div class="col-md-5 col-6">
                  <img
                    v-if="product.giftBoxType"
                    :src="`http://localhost:5000/${product.giftBox.images[0].path}`"
                    alt="..."
                    class="img-fluid rounded shadow"
                  />
                  <img
                    v-else
                    :src="`http://localhost:5000/${product.box.image[0].path}`"
                    alt="..."
                    class="img-fluid rounded shadow"
                  />
                </div>
                <div class="media-body">
                  <h2 class="h6 mb-0">
                    {{
                      product.giftBoxType ? product.giftBox.title : "Build Box"
                    }}
                  </h2>
                </div>
                <div class="media-body text-right">
                  <span
                    ><i class="fa-light fa-crown"></i> {{ product.price }}</span
                  >
                </div>
              </div>
              <!-- <hr class="line-info mb-5" />
              <form class="code-validate">
                <label>Discount</label>
                <div class="input-group">
                  <input
                    type="text"
                    class="form-control"
                    name="name"
                    placeholder="Discount Code"
                    aria-label="Discount"
                  />
                  <div class="input-group-append">
                    <button type="submit" class="btn btn-info">Apply</button>
                  </div>
                </div>
              </form> -->
              <hr class="line-info mb-3" />
              <div class="media align-items-center">
                <h3 class="h6 text-secondary mr-3">delsumma</h3>
                <div class="media-body text-right">
                  <span><i class="fa-light fa-crown"></i> {{ price }}</span>
                </div>
              </div>
              <div class="media align-items-center">
                <h3 class="h6 text-secondary mr-3">Frakt</h3>
                <div class="media-body text-right">
                  <span><i class="fa-light fa-crown"></i> 260</span>
                </div>
              </div>
              <hr class="line-info mb-3" />
              <div class="media align-items-center">
                <h3 class="h6">Totalt</h3>
                <div class="media-body text-right">
                  <span class="font-weight-semi-bold"
                    ><i class="fa-light fa-crown"></i> {{ price + 260 }}</span
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <form class="js-validate">
            <div class="container">
              <h3 class="title text-dark">Leverans address</h3>
              <div class="row">
                <div class="col-md-12">
                  <label class="labels">
                    namn
                    <span class="text-danger">*</span>
                  </label>
                  <input
                    type="text"
                    class="form-control"
                    name="name"
                    placeholder="namn"
                    v-model="form.name"
                  />
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-6">
                  <div class="js-form-message mb-6">
                    <label class="labels">
                      E-postadress
                      <span class="text-danger">*</span>
                    </label>
                    <input
                      type="email"
                      class="form-control"
                      name="email"
                      placeholder="E-postadress"
                      v-model="form.email"
                    />
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="js-form-message mb-6">
                    <label class="labels">
                      Mobil
                      <span class="text-danger">*</span>
                    </label>
                    <input
                      type="text"
                      class="form-control"
                      name="mobile"
                      placeholder="Mobil"
                      v-model="form.mobile"
                    />
                  </div>
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-8">
                  <div class="js-form-message mb-6">
                    <label class="labels">
                      Adress
                      <span class="text-danger">*</span>
                    </label>
                    <input
                      type="text"
                      class="form-control"
                      name="streetAddress"
                      placeholder="Adress"
                      v-model="form.address"
                    />
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="js-form-message mb-6">
                    <label class="labels">
                      Postnummer
                      <span class="text-danger">*</span>
                    </label>
                    <input
                      type="text"
                      class="form-control"
                      name="postalCode"
                      placeholder="Postnummer"
                      v-model="form.postalCode"
                    />
                  </div>
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="country"
                    >Land:
                    <span class="text-danger">*</span>
                  </label>
                  <select
                    class="form-control bg-dark"
                    id="country"
                    v-model="form.country"
                  >
                    <option value="" disabled>Välj land ...</option>
                    <option value="sweden">Sweden</option>
                  </select>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="city"
                    >Stad:
                    <span class="text-danger">*</span>
                  </label>
                  <select
                    class="form-control bg-dark"
                    id="city"
                    v-model="form.city"
                  >
                    <option value="" disabled>Välj din stad ...</option>
                    <option v-for="(city, i) in cities" :key="i" :value="city">
                      {{ city }}
                    </option>
                  </select>
                </div>
              </div>
              <validations-errors :errors="errors" />
              <button
                class="btn btn-primary btn-block my-3"
                @click.prevent="submit"
              >
                Beställ!
              </button>
              <hr />
              <div v-show="showPayment">
                <h4 class="title text-dark">Payment method</h4>
                <div
                  class="nav nav-tabs nav-tabs-primary btn-group"
                  role="tablist"
                >
                  <a
                    class="btn btn-sm btn-dark btn-simple active"
                    data-toggle="tab"
                    href="#link1"
                    role="tablist"
                  >
                    PayPal
                  </a>
                  <a
                    class="btn btn-sm btn-dark btn-simple"
                    data-toggle="tab"
                    href="#link2"
                    role="tablist"
                  >
                    Klarna
                  </a>
                </div>
                <div class="tab-content tab-space">
                  <div id="link1" class="tab-pane active">
                    <Payment
                      :price="price"
                      :showPaypalButton="isPaypalPayment"
                      :form="form"
                    />
                  </div>
                  <div id="link2" class="tab-pane">
                    <payment-klarna
                      :orders="cart"
                      :price="price"
                      :form="form"
                    />
                    <!-- <h5>Send payment to:</h5>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Name or email"
                      required=""
                    />
                    <br />
                    <button type="submit" class="btn btn-info btn-sm">
                      Pay with Klarna
                    </button> -->
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <Footer />
</template>

<script>
import { ref, watchEffect } from "@vue/runtime-core";
import { useRouter } from "vue-router";
import { useStore } from "vuex";
import api from "@/api";

//Import Components
import Nav from "@/components/layouts/Nav.vue";
import Footer from "@/components/layouts/Footer.vue";
import ValidationsErrors from "@/components/layouts/ValidationsErrors.vue";
import Payment from "@/components/layouts/Payment.vue";
import PaymentKlarna from "../components/layouts/PaymentKlarna.vue";

export default {
  components: { Nav, Footer, ValidationsErrors, Payment, PaymentKlarna },
  setup() {
    const store = useStore();
    const router = useRouter();

    const cart = ref([]);
    const price = ref(0);
    const isPaypalPayment = ref(false);
    const showPayment = ref(false);
    const form = ref({
      name: "",
      email: "",
      mobile: "",
      country: "sweden",
      city: "",
      address: "",
      postalCode: "",
    });
    const cities = [
      "Aby",
      "AElmhult",
      "AElvdalen",
      "AElvkarleby",
      "AElvsbyn",
      "Agnesberg",
      "Agunnaryd",
      "Akarp",
      "Akers Styckebruk",
      "Akersberga",
      "Alafors",
      "Alandsbro",
      "Aled",
      "Alem",
      "Alfta",
      "Alingsas",
      "Allerum",
      "Almeboda",
      "Almunge",
      "Alno",
      "Alsen",
      "Alsterbro",
      "Alstermo",
      "Alta",
      "Altersbruk",
      "Alunda",
      "Alvangen",
      "Alvesta",
      "Alvsjo",
      "Amal",
      "Ambjornarp",
      "Amotfors",
      "Anderslov",
      "Anderstorp",
      "Aneby",
      "Ange",
      "Angered",
      "Ankarsrum",
      "Ankarsvik",
      "Annelov",
      "Annerstad",
      "Ansvar",
      "Aplared",
      "Arboga",
      "Arbra",
      "Arholma",
      "Arjaeng",
      "Arjeplog",
      "Arkelstorp",
      "Arla",
      "Arloev",
      "Arnasvall",
      "Arsunda",
      "Arvidsjaur",
      "Arvika",
      "Aryd",
      "As",
      "Asa",
      "Asarna",
      "Asarum",
      "Asbro",
      "Aseda",
      "Asele",
      "Asenhoga",
      "Asensbruk",
      "Ashammar",
      "Askersund",
      "Askim",
      "Askloster",
      "Asmundtorp",
      "Aspas",
      "Aspered",
      "Aspero",
      "Astorp",
      "Atorp",
      "Atran",
      "Atvidaberg",
      "Avesta",
      "Axvall",
      "Backa",
      "Backaryd",
      "Backe",
      "Backefors",
      "Balinge",
      "Ballingslov",
      "Balsta",
      "Bankeryd",
      "Bara",
      "Barkarby",
      "Barseback",
      "Barsebackshamn",
      "Bastad",
      "Beddinge Lage",
      "Bengtsfors",
      "Berga",
      "Bergeforsen",
      "Bergkvara",
      "Bergshamra",
      "Bergsjoe",
      "Bergvik",
      "Bettna",
      "Billdal",
      "Billeberga",
      "Billesholm",
      "Billinge",
      "Billingsfors",
      "Bjarnum",
      "Bjarred",
      "Bjartra",
      "Bjasta",
      "Bjorbo",
      "Bjoringe",
      "Bjorkhaga",
      "Bjorklinge",
      "Bjorkoby",
      "Bjorkvik",
      "Bjorna",
      "Bjorneborg",
      "Bjornlunda",
      "Bjuraker",
      "Bjurholm",
      "Bjursas",
      "Bjuv",
      "Blackstad",
      "Blasmark",
      "Blattnicksele",
      "Blentarp",
      "Bockara",
      "Bodafors",
      "Boden",
      "Bofors",
      "Bohus",
      "Boliden",
      "Bollebygd",
      "Bollnas",
      "Bollstabruk",
      "Bor",
      "Borensberg",
      "Borghamn",
      "Borgholm",
      "Borgstena",
      "Borrby",
      "Botsmark",
      "Bottnaryd",
      "Boxholm",
      "Braas",
      "Braecke",
      "Brakne-Hoby",
      "Bralanda",
      "Bramhult",
      "Branno",
      "Brastad",
      "Bredared",
      "Bredaryd",
      "Bro",
      "Broby",
      "Brokind",
      "Bromma",
      "Bromoella",
      "Brosarp",
      "Brottby",
      "Brunflo",
      "Brunnby",
      "Bua",
      "Bullmark",
      "Bunkeflostrand",
      "Burea",
      "Burtraesk",
      "Bygdea",
      "Bygdsiljum",
      "Byske",
      "Charlottenberg",
      "Dala-Floda",
      "Dala-Jarna",
      "Dalaro",
      "Dalby",
      "Dals Langed",
      "Dals Rostock",
      "Dalsjofors",
      "Dalstorp",
      "Danderyd",
      "Degeberga",
      "Degerfors",
      "Deje",
      "Delsbo",
      "Dikanaes",
      "Dingle",
      "Dio",
      "Djura",
      "Djuras",
      "Djurhamn",
      "Djursholm",
      "Domsjo",
      "Donso",
      "Dorotea",
      "Dosjebro",
      "Drottningholm",
      "Duved",
      "Dyltabruk",
      "Ed",
      "Edsbro",
      "Edsbyn",
      "Edsele",
      "Edshultshall",
      "Edsvalla",
      "Ekeby",
      "Ekenassjon",
      "Ekshaerad",
      "Eksjoe",
      "Eldsberga",
      "Elloes",
      "Emmaboda",
      "Enanger",
      "Enebyberg",
      "Eneryda",
      "Enkoping",
      "Enskede-Arsta-Vantoer",
      "Enviken",
      "Erikslund",
      "Eriksmala",
      "Eskilstuna",
      "Eslov",
      "Faergelanda",
      "Faerjestaden",
      "Fagelfors",
      "Fageras",
      "Fagerberg",
      "Fagered",
      "Fagerhult",
      "Fagersanna",
      "Fagersta",
      "Fagervik",
      "Falkenberg",
      "Fallfors",
      "Falun",
      "Farbo",
      "Farila",
      "Farlov",
      "Farna",
      "Farnas",
      "Faro",
      "Fellingsbro",
      "Fengersfors",
      "Figeholm",
      "Filipstad",
      "Finja",
      "Finnerodja",
      "Finspang",
      "Fiskeby",
      "Fjaeras station",
      "Fjalkinge",
      "Fjardhundra",
      "Fjugesta",
      "Flen",
      "Fleninge",
      "Flisby",
      "Floby",
      "Floda",
      "Flyinge",
      "Follinge",
      "Fors",
      "Forsa",
      "Forsbacka",
      "Forsby",
      "Forserum",
      "Forshaga",
      "Forsheda",
      "Forslov",
      "Frandefors",
      "Fransta",
      "Fredriksberg",
      "Frillesas",
      "Fristad",
      "Fritsla",
      "Froso",
      "Frovi",
      "Frufallan",
      "Furulund",
      "Furuvik",
      "Gabo",
      "Gagnef",
      "Gallo",
      "Gallstad",
      "Gamla stan",
      "Gamleby",
      "Gammelstad",
      "Ganghester",
      "Gards Kopinge",
      "Gargnas",
      "Garpenberg",
      "Garphyttan",
      "Garsas",
      "Garsnas",
      "Gemla",
      "Genarp",
      "Genevad",
      "Getinge",
      "Gidea",
      "Gimo",
      "Gislaved",
      "Glanshammar",
      "Glimakra",
      "Glommen",
      "Glommerstrask",
      "Glostorp",
      "Glumslov",
      "Gnarp",
      "Gnesta",
      "Gnosjoe",
      "Goetene",
      "Gota",
      "Gothenburg",
      "Grabo",
      "Graddo",
      "Graestorp",
      "Grangarde",
      "Grangesberg",
      "Grasmyr",
      "Graso",
      "Grebbestad",
      "Grillby",
      "Grimeton",
      "Grimsas",
      "Grimslov",
      "Grimstorp",
      "Grisslehamn",
      "Grondal",
      "Gronskara",
      "Grums",
      "Grundsund",
      "Grycksbo",
      "Gryt",
      "Grythyttan",
      "Gualov",
      "Guldsmedshyttan",
      "Gullbrandstorp",
      "Gullspang",
      "Gunnebo",
      "Gunnilse",
      "Gusselby",
      "Gustafs",
      "Gustavsberg",
      "Gusum",
      "Gyttorp",
      "Hackas",
      "Hacksvik",
      "Haegersten",
      "Haellefors",
      "Haerryda",
      "Haesselby",
      "Hagfors",
      "Hagglund",
      "Hajom",
      "Hakkas",
      "Haknas",
      "Haljarp",
      "Hallabro",
      "Halland",
      "Hallarod",
      "Hallberg",
      "Halleforsnas",
      "Hallekis",
      "Hallestad",
      "Hallevadsholm",
      "Hallingsjo",
      "Hallsberg",
      "Hallsta",
      "Hallstahammar",
      "Hallstavik",
      "Halmstad",
      "Halso",
      "Halta",
      "Hamburgsund",
      "Hammar",
      "Hammaro",
      "Hammarstrand",
      "Hammenhog",
      "Hammerdal",
      "Hamneda",
      "Hamrangefjarden",
      "Hanaskog",
      "Handen",
      "Haparanda",
      "Harads",
      "Harbo",
      "Harby",
      "Harestad",
      "Harmanger",
      "Harplinge",
      "Harslov",
      "Hasselby",
      "Hasselfors",
      "Hasslarp",
      "Hasslo",
      "Hastveda",
      "Havdhem",
      "Hebo",
      "Hedared",
      "Hede",
      "Hedekas",
      "Hedemora",
      "Hedesunda",
      "Helgum",
      "Helsingborg",
      "Hemmingsmark",
      "Hemse",
      "Henan",
      "Herrangen",
      "Herrljunga",
      "Hestra",
      "Hillared",
      "Hillerstorp",
      "Hindas",
      "Hjaerup",
      "Hjalteby",
      "Hjarnarp",
      "Hjartum",
      "Hjo",
      "Hoegsby",
      "Hoeoer",
      "Hoerby",
      "Hoernefors",
      "Hofors",
      "Hoganas",
      "Hogsaters",
      "Hogsjo",
      "Hok",
      "Hokerum",
      "Hollviken",
      "Holmen",
      "Holmsjo",
      "Holmsund",
      "Holmsveden",
      "Holo",
      "Holsbybrunn",
      "Holsljunga",
      "Hono",
      "Horn",
      "Horndal",
      "Horred",
      "Hortlax",
      "Hova",
      "Hovas",
      "Hoviksnas",
      "Hovmantorp",
      "Huarod",
      "Huddinge",
      "Hudiksvall",
      "Hultafors",
      "Hultsfred",
      "Hunnebostrand",
      "Hunnestad",
      "Huskvarna",
      "Husum",
      "Hyllinge",
      "Hyltebruk",
      "Hyssna",
      "Iggesund",
      "Immeln",
      "Indal",
      "Ingarp",
      "Ingelstad",
      "Ingmarso",
      "Insjon",
      "Jaemjoe",
      "Jaervsoe",
      "Jamshog",
      "Jarbo",
      "Jarlasa",
      "Jarna",
      "Jarpen",
      "Jarved",
      "Joern",
      "Johanneshov",
      "Johannishus",
      "Jokkmokk",
      "Jonaker",
      "Jonsered",
      "Jordbro",
      "Jorlanda",
      "Jude",
      "Junosuando",
      "Kaevlinge",
      "Kage",
      "Kagerod",
      "Kalix",
      "Kallby",
      "Kallered",
      "Kallinge",
      "Kallo",
      "Kalmar",
      "Kareby",
      "Karesuando",
      "Karl Gustav",
      "Karlsborg",
      "Karlshamn",
      "Karlskoga",
      "Karlskrona",
      "Karlstad",
      "Karna",
      "Karra",
      "Katrineholm",
      "Kattarp",
      "Katthammarsvik",
      "Kattilstorp",
      "Kil",
      "Kilafors",
      "Killeberg",
      "Kimstad",
      "Kinna",
      "Kinnared",
      "Kinnarp",
      "Kiruna",
      "Kisa",
      "Kista",
      "Kivik",
      "Kladesholmen",
      "Klagerup",
      "Klagshamn",
      "Klagstorp",
      "Klassbol",
      "Klavrestrom",
      "Klintehamn",
      "Klippan",
      "Klovedal",
      "Knared",
      "Knislinge",
      "Knivsta",
      "Knutby",
      "Kode",
      "Kolback",
      "Kolmarden",
      "Kolsva",
      "Konga",
      "Koping",
      "Kopingebro",
      "Kopmanholmen",
      "Kopparberg",
      "Koppom",
      "Korpilombolo",
      "Korsberga",
      "Korskrogen",
      "Koskullskulle",
      "Kosta",
      "Kramfors",
      "Kristdala",
      "Kristianstad",
      "Kristineberg",
      "Kristinehamn",
      "Krokom",
      "Krylbo",
      "Kulla",
      "Kullavik",
      "Kulltorp",
      "Kumla",
      "Kungsaengen",
      "Kungsbacka",
      "Kungsgarden",
      "Kungshamn",
      "Kungsoer",
      "Kvanum",
      "Kvibille",
      "Kvicksund",
      "Kvidinge",
      "Kvissleby",
      "Kyrkobyn",
      "Lagan",
      "Laholm",
      "Lammhult",
      "Landeryd",
      "Landfjarden",
      "Landsbro",
      "Landskrona",
      "Landvetter",
      "Langas",
      "Langasjo",
      "Langhem",
      "Langsele",
      "Langshyttan",
      "Langviksmon",
      "Lanna",
      "Lannavaara",
      "Larbro",
      "Larv",
      "Lavsjo",
      "Laxa",
      "Lekeryd",
      "Leksand",
      "Lenhovda",
      "Lerberget",
      "Lerdala",
      "Lerum",
      "Lessebo",
      "Liden",
      "Lidhult",
      "Lidingoe",
      "Lidkoping",
      "Likenas",
      "Lilla Edet",
      "Lillpite",
      "Lima",
      "Limhamn",
      "Limmared",
      "Lindas",
      "Lindesberg",
      "Lindome",
      "Linghem",
      "Linneryd",
      "Listerby",
      "Lit",
      "Ljugarn",
      "Ljung",
      "Ljungaverk",
      "Ljungby",
      "Ljungbyhed",
      "Ljungbyholm",
      "Ljungsarp",
      "Ljungsbro",
      "Ljungskile",
      "Ljusdal",
      "Ljusfallshammar",
      "Ljusne",
      "Ljustero",
      "Ljustorp",
      "Loberod",
      "Loddekopinge",
      "Loderup",
      "Lodose",
      "Lomma",
      "Lonashult",
      "Lonsboda",
      "Los",
      "Lotorp",
      "Lottorp",
      "Lovanger",
      "Lovestad",
      "Lovikka",
      "Ludvigsborg",
      "Ludvika",
      "Lugnvik",
      "Lund",
      "Lycke",
      "Lyckeby",
      "Lycksele",
      "Lysekil",
      "Lysvik",
      "Mala",
      "Maleras",
      "Malilla",
      "Malma",
      "Malmback",
      "Malmberget",
      "Malmkoping",
      "Malmo",
      "Malsryd",
      "Malung",
      "Mankarbo",
      "Mansarp",
      "Mantorp",
      "Marback",
      "Mardaklev",
      "Mariannelund",
      "Mariefred",
      "Marieholm",
      "Mariestad",
      "Markaryd",
      "Marma",
      "Marsta",
      "Marstrand",
      "Matfors",
      "Mellansel",
      "Mellbystrand",
      "Mellerud",
      "Mjallom",
      "Mjolby",
      "Mockfjard",
      "Moelle",
      "Moelndal",
      "Moensteras",
      "Moerbylanga",
      "Moheda",
      "Moholm",
      "Moliden",
      "Molkom",
      "Molltorp",
      "Molnbo",
      "Molnlycke",
      "Mora",
      "Morarp",
      "Morgongava",
      "Morlunda",
      "Morrum",
      "Morsil",
      "Morup",
      "Motala",
      "Mullhyttan",
      "Mullsjoe",
      "Munka-Ljungby",
      "Munkedal",
      "Munkfors",
      "Musko",
      "Myggenas",
      "Myresjo",
      "Nacka",
      "Nalden",
      "Nashulta",
      "Nassjo",
      "Nasum",
      "Nasviken",
      "Nattraby",
      "Navekvarn",
      "Navlinge",
      "Nissafors",
      "Njurundabommen",
      "Njutanger",
      "Nodinge",
      "Nodinge-Nol",
      "Nora",
      "Norberg",
      "Nordingra",
      "Nordmaling",
      "Norrahammar",
      "Norrala",
      "Norrfjarden",
      "Norrhult",
      "Norrsundet",
      "Norrtalje",
      "Norsborg",
      "Norsholm",
      "Norsjoe",
      "Nossebro",
      "Nybro",
      "Nygard",
      "Nyhammar",
      "Nyhamnslage",
      "Nykil",
      "Nykroppa",
      "Nykvarn",
      "Nyland",
      "Nynas",
      "Nynashamn",
      "Nysater",
      "Nyvang",
      "Obbola",
      "Ockelbo",
      "Odakra",
      "Odeborg",
      "Odensbacken",
      "OEckeroe",
      "OEdeshoeg",
      "OErkelljunga",
      "OEsterbymo",
      "OEstervala",
      "OEsthammar",
      "OEverkalix",
      "OEvertornea",
      "Ojebyn",
      "Ojersjo",
      "Olofstorp",
      "Olofstroem",
      "Olsfors",
      "Onnestad",
      "Orby",
      "Orbyhus",
      "Oregrund",
      "Ormaryd",
      "Orno",
      "Ornskoldsvik",
      "Orrefors",
      "Orsa",
      "Orsundsbro",
      "Orviken",
      "Osby",
      "Oskarshamn",
      "Oskarstrom",
      "Osmo",
      "Ostansjo",
      "Osterbybruk",
      "Osterhaninge",
      "Osterskar",
      "Ostra",
      "Ostra Frolunda",
      "Ostra Hindalebyn",
      "Ostra Karup",
      "Ostra Ryd",
      "Otterbacken",
      "Ovanaker",
      "Overhornas",
      "Overkovland",
      "Overlida",
      "Overum",
      "Oviken",
      "Oxaback",
      "Oxelosund",
      "Oxie",
      "Paarp",
      "Pajala",
      "Palange",
      "Palsboda",
      "Partille",
      "Paskallavik",
      "Perstorp",
      "Pilgrimstad",
      "Pixbo",
      "Raa",
      "Raettvik",
      "Ramdala",
      "Ramnas",
      "Ramsele",
      "Ramsjo",
      "Ramvik",
      "Ranea",
      "Rangedala",
      "Ransater",
      "Ransta",
      "Ravlanda",
      "Reftele",
      "Rejmyre",
      "Rekarne",
      "Rengsjo",
      "Reso",
      "Restad",
      "Riddarhyttan",
      "Rimbo",
      "Rimforsa",
      "Ring",
      "Ringarum",
      "Rinkaby",
      "Roback",
      "Robertsfors",
      "Rockneby",
      "Rodeby",
      "Roke",
      "Rolfstorp",
      "Romakloster",
      "Romelanda",
      "Ronnang",
      "Ronneby",
      "Ronninge",
      "Roro",
      "Rorvik",
      "Rosersberg",
      "Rosson",
      "Rostanga",
      "Rosvik",
      "Rotebro",
      "Rottne",
      "Ruda",
      "Rundvik",
      "Ryd",
      "Rydaholm",
      "Rydboholm",
      "Rydeback",
      "Rydobruk",
      "Rydsgard",
      "Ryssby",
      "Saeffle",
      "Saeter",
      "Saevar",
      "Saevast",
      "Saevsjoe",
      "Sagmyra",
      "Sala",
      "Saltsjo-Duvnas",
      "Saltsjobaden",
      "Sand",
      "Sandared",
      "Sandarne",
      "Sandby",
      "Sandhem",
      "Sandhult",
      "Sandviken",
      "Sankt Olof",
      "Saro",
      "Satila",
      "Savedalen",
      "Savsjostrom",
      "Saxtorp",
      "Segersta",
      "Seglora",
      "Segmon",
      "Sennan",
      "Sexdrega",
      "Sibbhult",
      "Sidensjo",
      "Sifferbo",
      "Sigtuna",
      "Siljansnas",
      "Simlangsdalen",
      "Simrishamn",
      "Sjalevad",
      "Sjoebo",
      "Sjomarken",
      "Sjotofta",
      "Sjovik",
      "Sjuntorp",
      "Ska",
      "Skaerhamn",
      "Skaerholmen",
      "Skallinge",
      "Skane",
      "Skanes Fagerhult",
      "Skanninge",
      "Skanor med Falsterbo",
      "Skara",
      "Skaraborg",
      "Skarblacka",
      "Skarplinge",
      "Skarpnaeck",
      "Skattkarr",
      "Skee",
      "Skelleftehamn",
      "Skene",
      "Skepplanda",
      "Skillingaryd",
      "Skillinge",
      "Skinnskatteberg",
      "Skivarp",
      "Skogas",
      "Skoghall",
      "Skogstorp",
      "Skoldinge",
      "Skollersta",
      "Skondal",
      "Skruv",
      "Skultuna",
      "Skummeslovsstrand",
      "Skurup",
      "Skyllberg",
      "Skyttorp",
      "Slite",
      "Sloinge",
      "Slottsbron",
      "Slutarp",
      "Smalandsstenar",
      "Smedjebacken",
      "Smedstorp",
      "Smoegen",
      "Soderakra",
      "Soderala",
      "Soderby",
      "Soderfors",
      "Sodergard",
      "Soderhamn",
      "Sodra Sandby",
      "Sodra Sunderbyn",
      "Sodra Vi",
      "Soederbaerke",
      "Soederkoeping",
      "Sollebrunn",
      "Solleftea",
      "Sollentuna",
      "Solna",
      "Sommen",
      "Soraker",
      "Sorberge",
      "Sorombacken",
      "Sorsele",
      "Sosdala",
      "Sovde",
      "Spanga",
      "Sparsor",
      "Spekerod",
      "Staffanstorp",
      "Stallarholmen",
      "Stalldalen",
      "Stanga",
      "Stehag",
      "Stenhamra",
      "Stenkullen",
      "Stensele",
      "Stenstorp",
      "Stenungsund",
      "Stigen",
      "Stigtomta",
      "Stjarnhov",
      "Stoby",
      "Stockaryd",
      "Stockholm",
      "Stocksund",
      "Stode",
      "Stollet",
      "Stora",
      "Stora Hoga",
      "Stora Mellosa",
      "Stora Skedvi",
      "Stora Vika",
      "Storebro",
      "Storfors",
      "Storlien",
      "Storuman",
      "Storvik",
      "Storvreta",
      "Stra",
      "Strangnas",
      "Stratjara",
      "Stravalla",
      "Stroemstad",
      "Stroemsund",
      "Stromsbruk",
      "Stromsholm",
      "Stromsnasbruk",
      "Strovelstorp",
      "Stugun",
      "Sturefors",
      "Sturko",
      "Styrso",
      "Sundborn",
      "Sundbyberg",
      "Sundsbruk",
      "Sundsvall",
      "Sunnansjo",
      "Sunne",
      "Sunnemo",
      "Surahammar",
      "Surte",
      "Svaloev",
      "Svaneholm",
      "Svanesund",
      "Svangsta",
      "Svardsjo",
      "Svarta",
      "Svartinge",
      "Svartsjo",
      "Svedala",
      "Sveg",
      "Svenljunga",
      "Svensbyn",
      "Svenshogen",
      "Svenstavik",
      "Taberg",
      "Taby",
      "Taenndalen",
      "Taernaby",
      "Taftea",
      "Tagarp",
      "Talje",
      "Taljo",
      "Tallasen",
      "Tallberg",
      "Tanumshede",
      "Tarnsjo",
      "Tavelsjo",
      "Teckomatorp",
      "Tegeltorp",
      "Tenhult",
      "Tibro",
      "Tidaholm",
      "Tidan",
      "Tierp",
      "Timmele",
      "Timmernabben",
      "Timmersdala",
      "Timra",
      "Tingsryd",
      "Tingstade",
      "Tjornarp",
      "Toecksfors",
      "Toere",
      "Toereboda",
      "Tolg",
      "Tollarp",
      "Tollered",
      "Tomelilla",
      "Torekov",
      "Tormestorp",
      "Torpshammar",
      "Torsaker",
      "Torsas",
      "Torsby",
      "Torshalla",
      "Torslanda",
      "Torup",
      "Tranas",
      "Tranemo",
      "Trangsund",
      "Transtrand",
      "Traryd",
      "Traslovslage",
      "Travad",
      "Trehorningsjo",
      "Trekanten",
      "Trelleborg",
      "Trollhattan",
      "Trosa",
      "Tullinge",
      "Tumba",
      "Tun",
      "Tungelsta",
      "Tvaaker",
      "Tvaralund",
      "Tving",
      "Tygelsjo",
      "Tyreso Strand",
      "Tyringe",
      "Tystberga",
      "Ucklum",
      "Uddebo",
      "Uddeholm",
      "Uddevalla",
      "Ugglarp",
      "Ullared",
      "Ulricehamn",
      "Ulrika",
      "Undersaker",
      "Unnaryd",
      "Uppharad",
      "Upplands Vasby",
      "Uppsala",
      "Urshult",
      "Ursviken",
      "Utansjo",
      "Uttran",
      "Vackelsang",
      "Vaddo",
      "Vaderstad",
      "Vadstena",
      "Vaeja",
      "Vaellingby",
      "Vaennaes",
      "Vaermdoe",
      "Vaggeryd",
      "Vagnharad",
      "Valadalen",
      "Valberg",
      "Valbo",
      "Valdemarsvik",
      "Valla",
      "Vallakra",
      "Vallda",
      "Vallentuna",
      "Vallsta",
      "Valskog",
      "Vanersborg",
      "Vankiva",
      "Vannasby",
      "Vansbro",
      "Vara",
      "Varberg",
      "Varby",
      "Varekil",
      "Vargarda",
      "Vargon",
      "Varing",
      "Varmland",
      "Varnamo",
      "Varnhem",
      "Varobacka",
      "Varsas",
      "Varsta",
      "Vartofta",
      "Vase",
      "Vassmolosa",
      "Vasterfarnebo",
      "Vasterljung",
      "Vastervik",
      "Vastra Amtervik",
      "Vastra Frolunda",
      "Vastra Karup",
      "Vastra Ramlosa",
      "Vastra Torup",
      "Vato",
      "Vattholma",
      "Vaxholm",
      "Vaxjo",
      "Vaxtorp",
      "Veberod",
      "Veddige",
      "Vedum",
      "Vega",
      "Vegby",
      "Veinge",
      "Vejbystrand",
      "Vellinge",
      "Vendelso",
      "Vessigebro",
      "Vetlanda",
      "Vidsel",
      "Vikarbyn",
      "Viken",
      "Vikingstad",
      "Vikmanshyttan",
      "Viksjofors",
      "Vilhelmina",
      "Villan",
      "Vimmerby",
      "Vinberg",
      "Vindeln",
      "Vingaker",
      "Vinninga",
      "Vinslov",
      "Vintrie",
      "Vintrosa",
      "Virsbo Bruk",
      "Virserum",
      "Visby",
      "Viskafors",
      "Vislanda",
      "Vissefjarda",
      "Vitaby",
      "Vittaryd",
      "Vittsjo",
      "Vollsjo",
      "Vrena",
      "Vreta Kloster",
      "Vretstorp",
      "Yngsjo",
      "Ystad",
      "Ytterby",
      "Zinkgruvan",
      "Bräkne-Hoby",
      "Hällevik",
      "Hasslö",
      "Jämjö",
      "Jämshög",
      "Karlshamns kommun",
      "Karlskrona Kommun",
      "Mjällby",
      "Mörrum",
      "Nättraby",
      "Olofström",
      "Olofströms Kommun",
      "Rödeby",
      "Ronneby Kommun",
      "Sölvesborg",
      "Sölvesborgs kommun",
      "Sturkö",
      "Svängsta",
      "Abborrberget",
      "Älvdalen",
      "Älvdalens kommun",
      "Avesta Kommun",
      "Bjursås",
      "Borlänge",
      "Borlänge Kommun",
      "Brunna",
      "Djurås",
      "Enbacka",
      "Falu kommun",
      "Gagnefs Kommun",
      "Grängesberg",
      "Hedemora Kommun",
      "Insjön",
      "Järna",
      "Långshyttan",
      "Leksands kommun",
      "Ludvika Kommun",
      "Malung-Sälens kommun",
      "Mockfjärd",
      "Mora Kommun",
      "Ornäs",
      "Orsa Kommun",
      "Rättvik",
      "Rättviks Kommun",
      "Romme",
      "Säter",
      "Säters Kommun",
      "Siljansnäs",
      "Smedby",
      "Smedjebackens Kommun",
      "Svärdsjö",
      "Vansbro Kommun",
      "Arbrå",
      "Årsunda",
      "Bergby",
      "Bergsjö",
      "Bollnäs",
      "Bollnäs Kommun",
      "Färila",
      "Gävle",
      "Gävle Kommun",
      "Hofors Kommun",
      "Hudiksvalls Kommun",
      "Järbo",
      "Järvsö",
      "Ljusdals Kommun",
      "Nordanstigs kommun",
      "Ockelbo Kommun",
      "Ovanåkers Kommun",
      "Sandvikens Kommun",
      "Söderhamn",
      "Söderhamns Kommun",
      "Sörforsa",
      "Gotland",
      "Vibble",
      "Åled",
      "Åsa",
      "Falkenbergs Kommun",
      "Fjärås kyrkby",
      "Frillesås",
      "Frösakull",
      "Fyllinge",
      "Halmstads Kommun",
      "Haverdal",
      "Hylte Kommun",
      "Knäred",
      "Kungsbacka Kommun",
      "Laholms Kommun",
      "Onsala",
      "Oskarström",
      "Särö",
      "Skrea",
      "Steninge",
      "Träslövsläge",
      "Trönninge",
      "Tvååker",
      "Varbergs Kommun",
      "Västra Hagen",
      "Aneby Kommun",
      "Ekenässjön",
      "Eksjö",
      "Eksjö Kommun",
      "Gislaveds Kommun",
      "Gnosjö",
      "Gnosjö Kommun",
      "Gränna",
      "Habo",
      "Habo Kommun",
      "Jönköping",
      "Jönköpings Kommun",
      "Kaxholmen",
      "Malmbäck",
      "Mullsjö",
      "Mullsjö kommun",
      "Nässjö",
      "Nässjö Kommun",
      "Odensjö",
      "Sävsjö",
      "Sävsjö Kommun",
      "Smålandsstenar",
      "Tranås",
      "Tranås Kommun",
      "Vaggeryds Kommun",
      "Värnamo",
      "Värnamo Kommun",
      "Vetlanda kommun",
      "Vrigstad",
      "Blomstermåla",
      "Borgholms Kommun",
      "Emmaboda Kommun",
      "Färjestaden",
      "Högsby",
      "Högsby Kommun",
      "Hultsfreds Kommun",
      "Kalmar Kommun",
      "Lindsdal",
      "Målilla",
      "Mönsterås",
      "Mönsterås Kommun",
      "Mörbylånga",
      "Mörbylånga Kommun",
      "Nybro Kommun",
      "Oskarshamns Kommun",
      "Överum",
      "Påskallavik",
      "Rinkabyholm",
      "Södra Sandby",
      "Södra Vi",
      "Torsås",
      "Torsås Kommun",
      "Västervik",
      "Västerviks Kommun",
      "Vimmerby Kommun",
      "Älmhult",
      "Älmhults Kommun",
      "Alvesta Kommun",
      "Åseda",
      "Braås",
      "Lessebo Kommun",
      "Ljungby Kommun",
      "Markaryds Kommun",
      "Strömsnäsbruk",
      "Tingsryds Kommun",
      "Uppvidinge Kommun",
      "Växjö",
      "Växjö Kommun",
      "Älvsbyn",
      "Älvsbyns Kommun",
      "Arjeplogs Kommun",
      "Arvidsjaurs Kommun",
      "Bergnäset",
      "Bergsviken",
      "Björkskatan",
      "Bodens Kommun",
      "Gällivare",
      "Gällivare kommun",
      "Haparanda Kommun",
      "Jokkmokks Kommun",
      "Kalix Kommun",
      "Kiruna Kommun",
      "Luleå",
      "Luleå kommun",
      "Marielund",
      "Norrfjärden",
      "Överkalix",
      "Överkalix Kommun",
      "Övertorneå",
      "Övertorneå Kommun",
      "Pajala Kommun",
      "Piteå",
      "Piteå Kommun",
      "Råneå",
      "Roknäs",
      "Rolfs",
      "Sävast",
      "Södra Sunderbyn",
      "Töre",
      "Åsbro",
      "Askersunds Kommun",
      "Degerfors Kommun",
      "Ekeby-Almby",
      "Frövi",
      "Hällabrottet",
      "Hällefors",
      "Hällefors Kommun",
      "Hallsbergs Kommun",
      "Hovsta",
      "Karlskoga Kommun",
      "Kumla Kommun",
      "Laxå",
      "Laxå Kommun",
      "Lekebergs Kommun",
      "Lindesbergs Kommun",
      "Ljusnarsbergs Kommun",
      "Nora Kommun",
      "Örebro",
      "Örebro Kommun",
      "Pålsboda",
      "Sköllersta",
      "Storå",
      "Åby",
      "Åtvidaberg",
      "Åtvidabergs Kommun",
      "Berg",
      "Boxholms Kommun",
      "Ekängen",
      "Finspång",
      "Finspångs Kommun",
      "Grebo",
      "Herrestad",
      "Jursla",
      "Kinda Kommun",
      "Krokek",
      "Lindö",
      "Linköping",
      "Linköpings Kommun",
      "Malmslätt",
      "Mjölby",
      "Mjölby Kommun",
      "Motala Kommun",
      "Norrköping",
      "Norrköpings Kommun",
      "Ödeshög",
      "Ödeshögs Kommun",
      "Österbymo",
      "Skänninge",
      "Skärblacka",
      "Söderköping",
      "Söderköpings Kommun",
      "Svärtinge",
      "Tallboda",
      "Vadstena Kommun",
      "Valdemarsviks Kommun",
      "Ydre Kommun",
      "Åhus",
      "Åkarp",
      "Anderslöv",
      "Ängelholm",
      "Ängelholms Kommun",
      "Arlöv",
      "Åstorp",
      "Åstorps Kommun",
      "Bårslöv",
      "Båstad",
      "Båstads Kommun",
      "Bjärnum",
      "Bjärred",
      "Bjuvs Kommun",
      "Bromölla",
      "Bromölla Kommun",
      "Burlövs Kommun",
      "Eslöv",
      "Eslövs Kommun",
      "Färlöv",
      "Fjälkinge",
      "Förslöv",
      "Gantofta",
      "Gärsnäs",
      "Glimåkra",
      "Glumslöv",
      "Häljarp",
      "Hässleholm",
      "Hässleholms Kommun",
      "Hästveda",
      "Hittarp",
      "Hjärnarp",
      "Hjärup",
      "Hofterup",
      "Höganäs",
      "Höganäs Kommun",
      "Hököpinge",
      "Höllviken",
      "Höör",
      "Höörs Kommun",
      "Hörby",
      "Hörby Kommun",
      "Jonstorp",
      "Kågeröd",
      "Kävlinge",
      "Kävlinge Kommun",
      "Klågerup",
      "Klippans Kommun",
      "Köpingebro",
      "Kristianstads kommun",
      "Ljunghusen",
      "Löberöd",
      "Löddeköpinge",
      "Lomma Kommun",
      "Lönsboda",
      "Lunds Kommun",
      "Malmö",
      "Mörarp",
      "Näsum",
      "Norra Åsum",
      "Ödåkra",
      "Önnestad",
      "Örkelljunga",
      "Örkelljunga Kommun",
      "Osby kommun",
      "Östra Göinge Kommun",
      "Östra Ljungby",
      "Påarp",
      "Perstorps Kommun",
      "Rydebäck",
      "Rydsgård",
      "Sätofta",
      "Saxtorpsskogen",
      "Simrishamns kommun",
      "Sjöbo",
      "Sjöbo Kommun",
      "Skanör med Falsterbo",
      "Skåre",
      "Skegrie",
      "Skurups Kommun",
      "Smygehamn",
      "Sösdala",
      "Staffanstorps Kommun",
      "Stångby",
      "Strövelstorp",
      "Svalöv",
      "Svalövs Kommun",
      "Svedala Kommun",
      "Tollarp1",
      "Tomelilla Kommun",
      "Trelleborgs Kommun",
      "Tygelsjö",
      "Valje",
      "Veberöd",
      "Vellinge Kommun",
      "Vinslöv",
      "Vittsjö",
      "Ystads Kommun",
      "Åkers Styckebruk",
      "Ärla",
      "Arnö",
      "Eskilstuna Kommun",
      "Flens Kommun",
      "Gnesta Kommun",
      "Hällbybrunn",
      "Hälleforsnäs",
      "Katrineholms Kommun",
      "Malmköping",
      "Nyköping",
      "Nyköpings Kommun",
      "Olstorp",
      "Oxelösund",
      "Oxelösunds Kommun",
      "Strängnäs",
      "Strängnäs Kommun",
      "Svalsta",
      "Torshälla",
      "Trosa Kommun",
      "Vagnhärad",
      "Vingåker",
      "Vingåkers Kommun",
      "Akalla",
      "Åkersberga",
      "Alby",
      "Älmsta",
      "Älta",
      "Årsta",
      "Bollmora",
      "Boo",
      "Botkyrka Kommun",
      "Brevik",
      "Brunn",
      "Dalarö",
      "Danderyds Kommun",
      "Djurö",
      "Ekerö",
      "Ekerö Kommun",
      "Eriksberg",
      "Fisksätra",
      "Fittja",
      "Gamla Stan",
      "Haninge",
      "Haninge Kommun",
      "Hemmesta",
      "Hölö",
      "Huddinge Kommun",
      "Jakobsberg",
      "Järfälla kommun",
      "Kopparmora",
      "Kummelnäs",
      "Kungsängen",
      "Kungsholmen",
      "Långvik",
      "Lidingö",
      "Lindholmen",
      "Märsta",
      "Mölnbo",
      "Mörtnäs",
      "Nacka Kommun",
      "Norrtälje",
      "Norrtälje Kommun",
      "Nykvarns Kommun",
      "Nynäshamn",
      "Nynäshamns kommun",
      "Ösmo",
      "Österåkers Kommun",
      "Östermalm",
      "Pershagen",
      "Råsunda",
      "Resarö",
      "Rindö",
      "Rönninge",
      "Salems Kommun",
      "Saltsjöbaden",
      "Segeltorp",
      "Sigtuna Kommun",
      "Södermalm",
      "Södertälje",
      "Södertälje Kommun",
      "Sollentuna Kommun",
      "Solna Kommun",
      "Stavsnäs",
      "Stockholms Kommun",
      "Strömma",
      "Sundbybergs Kommun",
      "Täby Kommun",
      "Tensta",
      "Tyresö Kommun",
      "Upplands Väsby",
      "Upplands Väsby kommun",
      "Upplands-Bro Kommun",
      "Vallentuna Kommun",
      "Vårby",
      "Värmdö Kommun",
      "Vårsta",
      "Vasastan",
      "Vaxholms Kommun",
      "Alsike",
      "Älvkarleby",
      "Älvkarleby Kommun",
      "Anneberg",
      "Bälinge",
      "Bålsta",
      "Björklinge",
      "Enköping",
      "Enköpings Kommun",
      "Gamla Uppsala",
      "Håbo kommun",
      "Heby",
      "Heby kommun",
      "Irsta",
      "Karlholmsbruk",
      "Knivsta Kommun",
      "Lövstalöt",
      "Marieberg",
      "Morgongåva",
      "Örbyhus",
      "Öregrund",
      "Örsundsbro",
      "Österbybruk",
      "Östervåla",
      "Östhammar",
      "Östhammars Kommun",
      "Sävja",
      "Skutskär",
      "Söderfors",
      "Tärnsjö",
      "Tierps kommun",
      "Uppsala Kommun",
      "Åmotfors",
      "Årjäng",
      "Årjängs Kommun",
      "Arvika Kommun",
      "Björneborg",
      "Eda kommun",
      "Ekshärad",
      "Filipstads Kommun",
      "Forshaga Kommun",
      "Grums Kommun",
      "Hagfors Kommun",
      "Hammarö Kommun",
      "Karlstads Kommun",
      "Kils Kommun",
      "Kristinehamns Kommun",
      "Munkfors Kommun",
      "Råtorp",
      "Säffle",
      "Säffle Kommun",
      "Skattkärr",
      "Storfors Kommun",
      "Sunne Kommun",
      "Töcksfors",
      "Torsby Kommun",
      "Vålberg",
      "Åsele",
      "Åsele Kommun",
      "Bjurholms Kommun",
      "Bureå",
      "Burträsk",
      "Dorotea Kommun",
      "Ersmark",
      "Hörnefors",
      "Kåge",
      "Långsele",
      "Lycksele kommun",
      "Malå",
      "Malå Kommun",
      "Nordmalings Kommun",
      "Norsjö",
      "Norsjö Kommun",
      "Röbäck",
      "Robertsfors Kommun",
      "Sävar",
      "Skellefteå",
      "Skellefteå Kommun",
      "Sorsele Kommun",
      "Storumans Kommun",
      "Täfteå",
      "Umeå",
      "Umeå Kommun",
      "Vännäs",
      "Vännäs Kommun",
      "Vännäsby",
      "Vilhelmina Kommun",
      "Vindelns Kommun",
      "Ånge",
      "Ånge kommun",
      "Ås",
      "Bjästa",
      "Bredbyn",
      "Fränsta",
      "Härnösand",
      "Härnösands Kommun",
      "Johannedal",
      "Köpmanholmen",
      "Kramfors Kommun",
      "Nolby",
      "Örnsköldsvik",
      "Örnsköldsviks Kommun",
      "Skottsund",
      "Sollefteå",
      "Sollefteå Kommun",
      "Söråker",
      "Stockvik",
      "Sundsvalls Kommun",
      "Timrå",
      "Timrå Kommun",
      "Vi",
      "Arboga Kommun",
      "Barkarö",
      "Dingtuna",
      "Enhagen-Ekbacken",
      "Fagersta Kommun",
      "Hallstahammars Kommun",
      "Hökåsen",
      "Kolbäck",
      "Köping",
      "Köpings Kommun",
      "Kungsör",
      "Kungsörs kommun",
      "Norbergs Kommun",
      "Ramnäs",
      "Sala kommun",
      "Skinnskattebergs Kommun",
      "Surahammars Kommun",
      "Tillberga",
      "Västerås",
      "Ale Kommun",
      "Alingsås",
      "Alingsås Kommun",
      "Älvängen",
      "Åmål",
      "Åmåls Kommun",
      "Andalen",
      "Annelund",
      "Bengtsfors Kommun",
      "Björboholm",
      "Björkö",
      "Björlanda",
      "Bollebygds Kommun",
      "Borås",
      "Brålanda",
      "Dals Långed",
      "Dals-Ed Kommun",
      "Dalsjöfors",
      "Diseröd",
      "Donsö",
      "Ellös",
      "Eriksbo",
      "Essunga Kommun",
      "Falköping",
      "Falköpings Kommun",
      "Färgelanda",
      "Färgelanda Kommun",
      "Gånghester",
      "Gårdsten",
      "Göta",
      "Göteborg",
      "Göteborgs stad",
      "Götene",
      "Götene Kommun",
      "Gråbo",
      "Grästorp",
      "Grästorps Kommun",
      "Gullspång",
      "Gullspångs Kommun",
      "Hammarkullen",
      "Härryda Kommun",
      "Henån",
      "Herrljunga Kommun",
      "Hindås",
      "Hjo Kommun",
      "Hjuvik",
      "Hönö",
      "Höviksnäs",
      "Ingared",
      "Jörlanda",
      "Källby",
      "Kållered",
      "Karlsborgs Kommun",
      "Kungälv",
      "Kungälvs Kommun",
      "Kvänum",
      "Länghem",
      "Lerums Kommun",
      "Lidköping",
      "Lidköpings Kommun",
      "Lilla Edets Kommun",
      "Lödöse",
      "Lövgärdet",
      "Lysekils Kommun",
      "Majorna",
      "Mariestads Kommun",
      "Marks Kommun",
      "Melleruds Kommun",
      "Mölltorp",
      "Mölndal",
      "Mölndals kommun",
      "Mölnlycke",
      "Munkedals Kommun",
      "Myggenäs",
      "Nolvik",
      "Öckerö",
      "Öckerö Kommun",
      "Ödsmål",
      "Öjersjö",
      "Orust",
      "Partille Kommun",
      "Rannebergen",
      "Rävlanda",
      "Rönnäng",
      "Sålanda",
      "Sätila",
      "Sjömarken",
      "Skara Kommun",
      "Skärhamn",
      "Skövde",
      "Skövde Kommun",
      "Skultorp",
      "Smögen",
      "Sotenäs Kommun",
      "Stenungsunds Kommun",
      "Stöpen",
      "Stora Höga",
      "Strömstad",
      "Strömstads Kommun",
      "Styrsö",
      "Svenljunga Kommun",
      "Tanums Kommun",
      "Tibro Kommun",
      "Tidaholms kommun",
      "Tjörns Kommun",
      "Tjuvkil",
      "Töreboda",
      "Töreboda Kommun",
      "Tranemo Kommun",
      "Trollhättan",
      "Uddevalla Kommun",
      "Ulricehamns Kommun",
      "Vänersborg",
      "Vänersborgs Kommun",
      "Vara Kommun",
      "Vårgårda",
      "Vårgårda Kommun",
      "Vargön",
      "Västra Frölunda",
    ];
    const errors = ref([]);

    watchEffect(() => {
      if (store.getters.login !== null) {
        if (!store.getters.login) {
          router.push({ name: "Home" });
        }
      }
    });

    store.dispatch("loading", true);
    watchEffect(() => {
      if (store.getters.user.token) {
        api
          .get(`/cart`, {
            headers: { token: store.getters.user.token },
          })
          .then((res) => {
            cart.value = res.data.data.products;
            price.value = res.data.data.price;
            store.dispatch("loading", false);
            if (cart.value.length === 0) {
              router.push({ name: "Home" });
            }
          })
          .catch((err) => {
            console.log(err.response);
            store.dispatch("loading", false);
          });
      }
    });

    function submit() {
      store.dispatch("loading", true);
      api
        .post(`/orders/check`, form.value, {
          headers: { token: store.getters.user.token },
        })
        .then(() => {
          store.dispatch("loading", false);
          showPayment.value = true;
          isPaypalPayment.value = true;
        })
        .catch((err) => {
          errors.value = err.response.data.data;
          store.dispatch("loading", false);
        });
    }

    return {
      cart,
      price,
      form,
      cities,
      submit,
      errors,
      isPaypalPayment,
      showPayment,
    };
  },
};
</script>

<style></style>
