export default{
    addBox({commit},payload){
        commit("addBox",payload);
    },
    addCard({commit},payload){
        commit("addCard",payload);
    },
    addGift({commit},payload){
        commit("addGift",payload);
    },
    delGift({commit},payload){
        commit("delGift",payload);
    },
    addGiftBox({commit},payload){
        commit("addGiftBox",payload);
    },
    delGiftBox({commit},payload){
        commit("delGiftBox",payload);
    },
    addMessage({commit},payload){
        commit("addMessage",payload);
    },
    changePrice({commit},payload){
        commit("changePrice",payload);
    },
    reset({commit}){
        commit("reset");
    },
}